Fix issue 42 test failure seen on Fedora 24 by work around
possibly SELinux related, see also e.g.
https://issues.apache.org/jira/browse/MAPREDUCE-2374

[main] INFO ch.vorburger.mariadb4j.DB - mysqld executable:
/tmp/MariaDB4j/base/bin/mysqld.exe
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.289
sec <<< FAILURE!
simulatedStartOSX(ch.vorburger.mariadb4j.StartSimulatedForAllPlatformsTest)
Time elapsed: 0.07 sec  <<< ERROR!
java.lang.RuntimeException: Error unpacking embedded DB
    at ch.vorburger.mariadb4j.DB.unpackEmbeddedDb(DB.java:307)
    at
ch.vorburger.mariadb4j.StartSimulatedForAllPlatformsTest.checkPlatformStart(StartSimulatedForAllPlatformsTest.java:63)
    at
ch.vorburger.mariadb4j.StartSimulatedForAllPlatformsTest.simulatedStartOSX(StartSimulatedForAllPlatformsTest.java:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at
org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at
org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at
org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at
org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at
org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at
org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at
org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.FileNotFoundException: /tmp/MariaDB4j/base/bin/mysqld
(Text file busy)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at
org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:360)
    at
org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:319)
    at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1552)
    at
org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:1528)
    at
org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1478)
    at
ch.vorburger.mariadb4j.Util.extractFromClasspathToFile(Util.java:133)
    at ch.vorburger.mariadb4j.DB.unpackEmbeddedDb(DB.java:299)
    ... 31 more